# Generated by Django 5.1.7 on 2025-03-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='shortener_s_short_c_a8767f_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['expiration_date'], name='shortener_s_expirat_681590_idx'),
        ),
    ]
