name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and start containers
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build

    - name: Run Tests
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.test.yml exec -T app pytest --cov=. --cov-report=xml

    - name: Copy coverage report from container
      run: |
        docker cp $(docker-compose ps -q app):/app/coverage.xml .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: Tear down containers
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.test.yml down
