name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: devdb
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a your_redis_password ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: your_redis_password
        command: ["redis-server", "--requirepass", "your_redis_password"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-redis

    - name: Run Tests
      env:
        SECRET_KEY: devsecretkey
        DEBUG: 1
        DB_HOST: localhost
        DB_NAME: devdb
        DB_USER: devuser
        DB_PASS: changeme
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_PASSWORD: your_redis_password
        PYTHONPATH: ${{ github.workspace }}/app
      run: |
        cd app
        python -m pytest
